### ISSUE TITLE
Activity dropdown list

### ISSUE THREAD

**Issue by andrewtpham** [mercycorps/tola-activity#13]
In each activity dropdown, include: Activity Code, Office Code, then Activity Name
![screen shot 2015-06-10 at 7 00 33 pm](https://cloud.githubusercontent.com/assets/4407063/8085002/33fa6dde-0fa3-11e5-82d7-ce793ef83917.png)

**Comment by glind** [comment]
Activity code is an optional field so it doesn't seem useful.  Office code and Activity name are done though.
