### ISSUE TITLE
Communities: Searchable communities to filter all proposals, agreements and completions linked to that community

### ISSUE THREAD

**Issue by andrewtpham** [mercycorps/tola-activity#14]
![screen shot 2015-06-10 at 7 11 10 pm](https://cloud.githubusercontent.com/assets/4407063/8085316/c0a0ce30-0fa4-11e5-9be5-c11a78005159.png)

**Comment by glind** [comment]
Searchable by all primary text fields in the community as well as agreement, proposal and complete.  But without display of these many to many relationships it will be confusing.
