### ISSUE TITLE
Communities: list of communities to display a field that shows which programs and activities are taking place at the project site

### ISSUE THREAD

**Issue by andrewtpham** [mercycorps/tola-activity#15]
Can remove approval field to make room for the new fields.
![screen shot 2015-06-10 at 9 30 16 pm](https://cloud.githubusercontent.com/assets/4407063/8088621/eb723d52-0fb7-11e5-9f17-0b3b338e83f4.png)

**Comment by glind** [comment]
I don't know that we want a list of Programs and proposals on this screen, but we could create a tab in the edit form that lists what programs/agreement etc. are linked to this community with links back to the agreements.
