### ISSUE TITLE
Indicators Grid Print "Export All" doesn't trigger any action

### ISSUE THREAD

**Issue by glind** [mercycorps/tola-activity#152]
clivingstone@cn.mercycorps.org When I click on the "Export All" button at the bottom of the Indicator Plan Grid Print nothing happens. No broken link pages is returned, but the Grid Print page seems to only refresh itself. No export/download is initiated.

**Comment by karrla** [comment]
#131 and #152 related

**Comment by karrla** [comment]
We are now getting the page not found in production 
and this exception in demo: Exception Value: 	
'Sector' object has no attribute 'name'

example grid report: https://tola-activity-demo.mercycorps.org/indicators/export/265/
