### ISSUE TITLE
Add land classification to Site Profile demographics tab

### ISSUE THREAD

**Issue by glind** [mercycorps/tola-activity#162]
glind@mercycorps.org We need to classify land types for each site.  It looks like the best place to add this would be the demographics tab with a field called Land Classification.  Values would be Rural, Urban, Peri-Urban and other?  My guess is we make this a managed field in the admin but universal so everyone uses the same classifications.

**Comment by joash** [comment]
Added a land classifier 'Land Type' to site profile and admin.
