### ISSUE TITLE
error when adding a new indicator

### ISSUE THREAD

**Issue by glind** [mercycorps/tola-activity#168]
skouzi@lb.mercycorps.org I was on the 'GAITID: 5717 - Psychosocial Support and Safe Access to Education for Youth' adding indicators and I clicked on save on the first page which requests to identify whether the indicator is a DIG indicator.  An error page then appears, attached below.

**Comment by karrla** [comment]
Error on "Save" when trying to create an indicator for any country/program.

**Comment by glind** [comment]
Yeah we have switched over to the Dig indicator service as well as TolaTables but the firewall permissions aren't quite set up yet.  Brian is working on it.

**Comment by glind** [comment]
We have a temporary fix in place until the DIG server can be reached again.

**Comment by karrla** [comment]
Create "Custom" indicator still errors.

**Comment by glind** [comment]
Custom now fixed as well
