### ISSUE TITLE
Program Indicator Form: Error when trying to add new data

### ISSUE THREAD

**Issue by andrewtpham** [mercycorps/tola-activity#18]
![screen shot 2015-06-15 at 11 27 27 am](https://cloud.githubusercontent.com/assets/4407063/8154663/b32e832c-1351-11e5-8fae-63ba0e666fd6.png)

**Comment by glind** [comment]
This is fixed but I would suggest we get rid of this and link off of the new indicator data page or indicators them selves to add new data.
