### ISSUE TITLE
Sending comments to GitHub

### ISSUE THREAD

**Issue by glind** [mercycorps/tola-activity#203]
Re-Opened

**Comment by glind** [comment]
amembaj@gmail.com Sending comments to GitHub     # <br/> AMEMBAJ@GMAIL.COM added a comment   - Updating the 'update issue in GitHub'

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM added a comment   - Updating the 'update issue in GitHub'

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM added a comment   - Updating the 'update issue in GitHub'

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM added a comment   - Updating the 'update issue in GitHub'

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM added a comment   - Updating the 'update issue in GitHub'

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM added a comment   - Updating the 'update issue in GitHub'

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM added a comment   - Another update

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM added a comment   - Another update

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM added a comment   - Another new comment to test capturing from text area

**Comment by glind** [comment]
weird comment

**Comment by glind** [comment]
weird comment

**Comment by glind** [comment]
weird things

**Comment by glind** [comment]
weird things

**Comment by glind** [comment]
weird things

**Comment by glind** [comment]
weird things

**Comment by glind** [comment]
weird things

**Comment by glind** [comment]
weird things

**Comment by glind** [comment]
weird things

**Comment by glind** [comment]
weird things

**Comment by glind** [comment]
weird things

**Comment by glind** [comment]
Data from text area

**Comment by glind** [comment]
Data from text area

**Comment by glind** [comment]
Data from text area

**Comment by glind** [comment]
Data from text area

**Comment by glind** [comment]
Data from text area

**Comment by glind** [comment]
Data from text area

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM changed ticket status from [Closed] to [ Re-Opened]

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM changed ticket status from [Closed] to [ Re-Opened]

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM changed ticket status from [Closed] to [ Re-Opened]

**Comment by glind** [comment]
AMEMBAJ@GMAIL.COM changed ticket status from [Reopened] to [ Closed]

**Comment by joash** [comment]
Comments were made by myself. Testing the user who sends comments.

**Comment by joash** [comment]
Reopen with some simple comments.
