### ISSUE TITLE
Home Dashboard

### ISSUE THREAD

**Issue by andrewtpham** [mercycorps/tola-activity#27]
Ability to click on the bar chart for activities by status such as "Open" to filter all open project activities. Same for pending, approved, etc.
![screen shot 2015-06-22 at 11 08 21 am](https://cloud.githubusercontent.com/assets/4407063/8276720/0739a672-18cf-11e5-8cce-8c6c9291fc9c.png)

**Comment by glind** [comment]
Links to agreements and completed report/list
