### ISSUE TITLE
Update Communities, Project Agreement and Project Completion Fields

### ISSUE THREAD

**Issue by andrewtpham** [mercycorps/tola-activity#32]
Revised all 3 core forms. Version 4 (July 2015) can be found:

Communities:
https://docs.google.com/document/d/1JCbcYA_qjspSE1ZLSUqfBgcebD7QwLZf8RX-FZAHqGI/edit#

Project Agreement:
https://docs.google.com/document/d/1E6oBo_H1eaxfTN6rtZSy1jyxfarazJ_4zYwtFfVU1cg/edit#

Project Completion:
https://docs.google.com/document/d/1J3f1dCJiM-b9vcOF-oYKFhIp1AiwzJl6dMHAhM-Uad8/edit

**Comment by glind** [comment]
This is a difficult way to manage changes in the form.  It's not clear what of these are changes or differences compared to the existing system.  We need to submit individual changes to a form and document the reason for the change.  That way we can document who made the request, why it needs to be done and what downstream affects it will have to reports, offline forms, print version, ONA etc.

**Comment by glind** [comment]
Are we still agreed that the Checklist should be a separate form and not part of the completion?

**Comment by andrewtpham** [comment]
yes, just need to have something that signals it at the end of completion
form
