### ISSUE TITLE
the project agreements are not usable while the project proposals are approved 

### ISSUE THREAD

**Issue by mcafg** [mercycorps/tola-activity#37]
![capture](https://cloud.githubusercontent.com/assets/12292210/8892929/18981584-338c-11e5-8546-159b1d2d29b7.PNG)
the project agreements are not usable while the project proposals are approved

**Comment by glind** [comment]
The example above shows a project proposal "In Progress" not Approved.  Once it is approved then the "create an agreement" button will be clickable.
