### ISSUE TITLE
Community Proposal: Add MC Community Proposal Description Field + Original Community Proposal Attached Field

### ISSUE THREAD

**Issue by andrewtpham** [mercycorps/tola-activity#44]
two fields missing.

Describe the project you would like the program to consider (Description must describe how the Community Proposal meets the project criteria)

Community Proposal Attached (Original proposal from the Community) 
[YES / NO]

Link to the Project Agreement Paper Form: https://docs.google.com/document/d/1E6oBo_H1eaxfTN6rtZSy1jyxfarazJ_4zYwtFfVU1cg/edit#

**Comment by glind** [comment]
This seems invalid with move to new documentation links

**Comment by andrewtpham** [comment]
Still think we should add the community description but add a link to the documents form instead to direct attachment

**Comment by glind** [comment]
Isn't the description in the agreement they would be attaching?  Seems like redundant information

**Comment by andrewtpham** [comment]
The description field is usually a translation from local language and the
attachment is something we use a proof but the description is something we
use in the system to get a report out on.
