### ISSUE TITLE
Dev to Production Migration: Proposal fields did not transfer over

### ISSUE THREAD

**Issue by andrewtpham** [mercycorps/tola-activity#45]
After the migration, similar fields that were in the production did not map over to the similar fields in the updated forms. This includes 1) office code, 2) community rep and #, 3) community mobilizer and # and 4) proposal description.

Since a lot of the proposal fields transferred over to the agreement after you initiated it, so wondering if that was a reason it was lost when we removed the old proposal form? Do you know if we can salvage any of the proposal data? In particular, the office code is needed so we can identify which proposal/agreement and go back to the soft copy to re-enter but without the office code + activity code (already there) it will be really difficult.

I've asked all staff to stop entering in new data into production for the time being until you're back and we've had a chance to look over this.

<img width="736" alt="screen shot 2015-08-13 at 1 37 33 pm" src="https://cloud.githubusercontent.com/assets/4407063/9246402/886ef8f4-41c0-11e5-827b-d9f7aff023d4.png">

**Comment by glind** [comment]
Any data that was only in a project proposal form wouldn't have migrated to project agreement.  The project agreement data was not removed it just never existed.  If a project agreement existed with an office code (very few if any did) it will still be there.  We did not add the office code to the project agreement until recently.

**Comment by NinetteA** [comment]
This might be a stupid question- but the communities with Office codes in demo should have mapped out in production, right?
demo:
<img width="1108" alt="screen shot 2015-08-20 at 3 07 38 pm" src="https://cloud.githubusercontent.com/assets/13760198/9381648/8a56e562-474e-11e5-868f-d5b20c3a94c3.png">
production:
<img width="1102" alt="screen shot 2015-08-20 at 3 17 29 pm" src="https://cloud.githubusercontent.com/assets/13760198/9381656/9f47fc90-474e-11e5-90e0-8d808382699d.png">

In demo its KNDAF04 but in production it has migrated as test-AF04. Maybe that's one of the reason why community representative info did not map out in the proposal agreement form?

**Comment by glind** [comment]
Well Demo and Production are two separate data sets so changes in one would not be reflected in the other.  So it's possible a change happened in demo and that is why the office codes are different for the same community.  Also the community representative in the agreement form is not connected to the Community form, though I'm not sure why we have an office code TEST in production.  It seems like they refer to the same office AF04.  Is it possible someone was testing the office admin tool and made a change to AF04 not knowing it would be saved?
