### ISSUE TITLE
Dashboard issue

### ISSUE THREAD

**Issue by mcafg** [mercycorps/tola-activity#46]
Hi- as you can see bellow link, while we are filtering the sector all dashboard should show us the result for the filtered sector but now we only can view the program for the filtered sector, not the maps.

https://drive.google.com/file/d/0B-rABO6yfs21bEZXS0lYUVczemc/view?usp=sharing 

Thanks
Mashal

**Comment by glind** [comment]
Dashboard now filters by sector across all sections not just the list of programs.
