### ISSUE TITLE
http://tola.work

### ISSUE THREAD

**Issue by mcafg** [mercycorps/tola-activity#58]
we want to add some issues in http://tola.work but the submit remote button is not working 
![01](https://cloud.githubusercontent.com/assets/12292210/9835559/8375687a-5a06-11e5-92b5-5b3ff629a5de.png)

**Comment by NinetteA** [comment]
Mashal, please login first. Then you should be able to submit issue. Hope this helps!

**Comment by mcafg** [comment]
thank you it is working

**Comment by glind** [comment]
Thanks for pointing this out, it will now ask you to login or register instead of throwing an unauthorized error.
