### ISSUE TITLE
Remove User Error

### ISSUE THREAD

**Issue by mcafg** [mercycorps/tola-activity#61]
as we have duplicate users,we need to delete one of them, which we are not able based on bellow error 

![user](https://cloud.githubusercontent.com/assets/12292210/9875128/e986475e-5bc0-11e5-981f-4919765d0e79.png)

**Comment by glind** [comment]
The approval authority table has been added back to the database so this should work.  Please be careful deleting users from the system though.  All users should be added and created via the SSO login from the MercyCorps server so there should not be any duplicate users.  The only need to modify a user profile at all should be to give or remove permissions.
