### ISSUE TITLE
Project Agreement: Add "Project Budget" (BoQ) link to document form

### ISSUE THREAD

**Issue by glind** [mercycorps/tola-activity#85]
per Brandy's request changing BoQ to Project Budget

**Comment by glind** [comment]
No Idea what BoQ is

**Comment by esinn** [comment]
Bill of Quantity - primarily for infrastructure projects

**Comment by glind** [comment]
Thanks.  I'm assuming Project Budget link to document form then is added via the documents section, so closing this issue.
