### ISSUE TITLE
Project Agreement: Remove " Checked by" and "Reviewed by" fields under Approval tab

### ISSUE THREAD

**Issue by glind** [mercycorps/tola-activity#93]
Add "Field Verification By" under approval tab

**Comment by andrewtpham** [comment]
Oops, I realized I didn't mentioned "Reviewed by date" also needs to change to "Field verification date". Can we also remove "Approval submitted by" I think we need to simplify the # of people needing to view this. The "Estimated by" field will tell us this already.
<img width="626" alt="screen shot 2015-09-30 at 3 46 18 pm" src="https://cloud.githubusercontent.com/assets/4407063/10194717/8d954a96-678a-11e5-8ea2-f9effe444cb0.png">
