### ISSUE TITLE
Community profile form- GPS error 

### ISSUE THREAD

**Issue by mcafg** [mercycorps/tola-activity#98]
in the community profile section Location Tab it has been written that the GPS point should be in decimal degree but, while I enter the decimal degree GPS point, it does not accept, may be we have to go and select from the map which is difficult to find the exact location, and we prefer to add the GPS number manually 

![image](https://cloud.githubusercontent.com/assets/12292210/10267333/3a9c4916-6aa5-11e5-93f1-e22b4a105206.png)

**Comment by glind** [comment]
This is actually only an issue for the Chrome browser

**Comment by mcafg** [comment]
Thank you the GPS point is working in explorer with decimal degree but still i am requesting you to fix issue #99 please.
