### ISSUE TITLE
in community Profile Tab 3 (for geographic communities) we need to change the yellow highlighted section 

### ISSUE THREAD

**Issue by mcafg** [mercycorps/tola-activity#99]
* change Population to Household 
* in Average landholding size we should have the permission to add decimal degree
* in literacy section we need to add percentage(%) for Number of literate males and females

![image](https://cloud.githubusercontent.com/assets/12292210/10276866/8ae864c8-6b67-11e5-81f1-a3157a6b67ad.png)

**Comment by joash** [comment]
Community Profile Form changed to Site Profile Form (Tola-Help ticket #113 Add new Form: 'Site Profile Form').
